### ISSUE TITLE
First feature:  dogecoin address handling

### ISSUE THREAD

**Issue by tjstebbing** [dogecoinfoundation/libdogecoin#1]
Perhaps it's easiest to start with a small vertical slice which is fairly well understood, and define some functions, write some code, write some tests, get some bindings working and ship a useful 0.1.0 version with a functional dogecoin address feature.

Keen to discuss what that would look like:

* Address validation (all types)
* Basic address generation 
* HD parent/child address generation / validation
* Address identification (documentation in the spec? all the options etc)
* test fixtures: a bunch of various addresses 
* bindings for golang / python / node?

**Comment by rnicoll** [comment]
Noting it might be worth looking at https://github.com/bitcoinj/bitcoinj/blob/master/core/src/main/java/org/bitcoinj/core/Address.java to inspire ideas.

**Comment by rnicoll** [comment]
Thoughts on what the final API should cover:

* Parse from text (requires some sort of "What to expect" object which contains the prefixes for the network the address belongs to)
* Generate from public key
* Generate from script
* Generate text (base 58) format address
* Get type (pay to key, pay to key hash, pay to script hash)

Bitcoinj extends `Address` into `LegacyAddress` and `SegwitAddress`, as we don't handle segwit I think we're safe enough to have a single address type.

HD is something a wallet component would track, when generating keys, typically the addresses contain the hash of a key rather than the key.
