### ISSUE TITLE
Configure fails without libunistring headers installed

### ISSUE THREAD

**Issue by chromatic** [dogecoinfoundation/libdogecoin#114]
I ran `./autogen.sh` and `./configure` with a fresh 0.1.2 download and received this output on 64-bit x86 Linux (Ubuntu 22.04):

```
...
checking for main in -lunistring... no
configure: error: libunistring missing
```

After installing `libunistring-dev`, the configuration process continued and `make` and `make check` succeeded.

I notice the address documentation recommends this dependency, but it appears that it's a requirement for configuration. 

That's fine for my purposes, but I'm building a binding that also installs libdogecoin, and managing another shared library and headers in addition will add some friction. The GNU library isn't licensed as permissively as libevent (see #65), but it does have a dual-license of GPL/LGPL, of which I believe libdogecoin chooses the latter approach.

**Comment by xanimo** [comment]
@edtubbs is working on making it an optional dependency so for the time being yes it is a requirement if self compiling. Outside that we've combined libunistring.a into libdogecoin.a as built from depends during gitian build so that would alleviate the burden of needing libunistring-dev for now but again for self compilation it's in the works.

**Comment by edtubbs** [comment]
@chromatic, we added a config option to disable libunistring functions. do you have any objections to closing this given that #115 and #118 have been merged?
